feat: env management commands
permitio/permit-cli pull request #37
Opened 2024-11-24 11:34 UTC by 35C4n0r

Closes #18 
/claim #18

2024-11-25 08:14 UTC, gemanor commented
@35C4n0r the lint has some errors..

2024-11-29 08:10 UTC, gemanor commented
Hey, some functional comments:
1. When running `env select` commands, and there's only one workspace or one project, it should skip the selection. For now, even if one project/environment is presented, it let's the user choose between them. Please ensure if there's only one element in a select step, it gets skipped.
2. In `copy` command, it is hard to get the env id. We should keep it in the same way we did with other commands. Using the select element. Please use the same SelectEnvironment that allows the user to select the environment they want to copy from a select element. Then, just ask for the name of the new environment and copy it.
3. In general, this `ink-form` makes things complex. The default should be copied to a new environment, and the form is just a wizard, the same as we do with other commands. Only in case that `--existing` argument is passed will the existing ID be asked for and copied.
4. Also, in the member command, please just use a wizard as we did in the login and such. The form is making the experience complex. If someone want's a form, then they can use it in the UI.

2024-11-29 08:34 UTC, gemanor commented
Please merge from main

2024-12-01 06:03 UTC, gemanor commented
Hey, @35C4n0r, the `copy` command does not work for me. Can you please test that?

2024-12-01 06:44 UTC, 35C4n0r commented
@gemanor, pushed a change that fixes the issue, It now handles the case when `--env-name` is not passed as a cli option

2024-12-01 11:17 UTC, gemanor commented
@35C4n0r, the scope is redundnat (just use the default), and the description/strategy should be also in the wizard, not only as variables

2024-12-01 14:43 UTC, 35C4n0r commented
@gemanor done!

2024-12-02 07:01 UTC, gemanor commented
The tests are failing now. Also, the success message is missing from the copy command.
Please make sure it is all passed and that you're running sanity tests on all the commands before asking review.

2024-12-02 07:02 UTC, gemanor commented
There are also many linting warning. Please ensure you're fixing the useEffect dependencies problems. Just use the standard practices like useCallback/useMemo and pure functions to avoid such.

2024-12-02 09:15 UTC, 35C4n0r commented
As for the warnings, if I don't want something to be the dependency of a useEffect, why should I add it in the dependency array?

2024-12-02 09:27 UTC, Abiji-2020 commented
> As for the warnings, if I don't want something to be the dependency of a useEffect, why should I add it in the dependency array?

instead of adding it as a dependency array, we can use `useCallback` or `useMemo` to overcome it, it was suggested by gemanor in early PR of mine.

2024-12-09 10:08 UTC, gemanor requested changes
Great job! Appreciate the effort!

Please address the comments and attach a sanity test video for the following flows after addressing them)

- Environment copy
  - To new one with a wizard
  - To a new one with variables provided (all provided, and partially provided - see CR)
  - To an existing environment that exists
  - To an existing environment that does not exist (fail)
- Invite member
  - With organization-level key
  - With project-level key
  - With wrong key
  - With environment-level key
  - With provided project/environment variables (see CR)
  - With an email that is already a member
- Environment select
  - With all optional values as variables
- Login flow on Windows (you said something about the port?)

2024-12-09 10:08 UTC, gemanor commented on source/hooks/useApiKeyApi.ts
> +export const useApiKeyApi = () => {
Could be use for all the API Key level errors etc.

2024-12-10 17:10 UTC, 35C4n0r commented on source/commands/env/member.tsx
> +export const options = zod.object({
I don't think we need `project` here, we get that either way from the apiKey, We'll just add environment.

2024-12-11 07:55 UTC, gemanor commented
@35C4n0r any updates on that?

2024-12-13 10:54 UTC, gemanor approved these changes
Good job, thanks!

2024-12-13 10:55 UTC, merged