#feat16 : Added command graph (browser based).
permitio/permit-cli pull request #45
Opened 2024-12-09 08:55 UTC by harshtech123

/claim #16
/closes #16 

CLI is now able to read the whole resource instance, relationships, and role assignment from the Permit APIs and display them as a graph with the relationships.

added command graph that runs on

npx tsx ./source/cli.tsx graph

display a permit fga graph that is showing the graph of the Permit permissions in ReBAC. 

opened in default browser
![Screenshot 2024-12-08 134007](https://github.com/user-attachments/assets/62fb7e81-1b24-4a3f-a02c-179d6a27f1e6)

2024-12-27 15:18 UTC, harshtech123 commented
implemented the fonts style and color as per permit color and fonts , plus followed the same way of zanzibar tuples as per our website. saved the "resource"/"role"/"user" repetitive text.
![Screenshot 2024-12-27 202354](https://github.com/user-attachments/assets/9c1ae065-68f9-4617-8b5e-03f00ba3a412)

2025-03-22 21:13 UTC, gemanor requested changes
The code is generally great, but it also needs some refactoring. Left comments.

2025-03-22 21:13 UTC, gemanor commented on source/components/HtmlGraphSaver.ts
> +	const htmlTemplate = `
Please extract it to an external HTML file and import it to the component

2025-03-22 21:13 UTC, gemanor commented on source/components/generateGraphData.ts
> +// Define types
The file name should be `GraphData.ts` or `GraphDataGenerator.ts`

2025-03-22 21:13 UTC, gemanor commented on source/components/graphCommand.tsx
> +import React, { useEffect, useState } from 'react';
This file should get refactored with the following comments in mind:
- File name should be `GraphCommands.tsx` or just `Graph.tsx`
- No API calls should made from here, but from hooks. See the contributing guide for the right usage of hooks, AuthProvider, and `useClient` to do API calls (you'll maybe need to merge from the main for that)
- Functions need to be more modular break to smaller, more maintainable functions

2025-03-24 11:55 UTC, harshtech123 commented on source/components/HtmlGraphSaver.ts
> +	const htmlTemplate = `
done

2025-03-24 11:55 UTC, harshtech123 commented on source/components/generateGraphData.ts
> +// Define types
changed , thank you!

2025-03-24 11:56 UTC, harshtech123 commented on source/components/graphCommand.tsx
> +import React, { useEffect, useState } from 'react';
named as GraphCommands.tsx and now using useClient for making api calls, thank you!

2025-03-27 19:27 UTC, gemanor approved these changes
Great Job! Thanks for this.

2025-03-27 19:28 UTC, merged